version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:linux-arm64-2.19.4-alpine
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /opt/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

